import type { House, Officer } from "@/lib/types"

// Dummy data for houses
export const houses: House[] = [
  {
    id: 1,
    beneficiaryName: "Tenzing Bhutia",
    district: "East Sikkim",
    village: "Gangtok",
    stage: "In Progress",
    progress: 60,
    fundUtilized: "Rs. 1,20,000",
    lat: 27.3314,
    lng: 88.6138,
    images: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    lastUpdated: "2023-12-15",
    startDate: "2023-08-10",
    expectedCompletion: "2024-06-30",
    contactNumber: "9876543210",
    aadharNumber: "XXXX-XXXX-1234",
    familyMembers: 4,
    assignedOfficer: "Karma Dorjee",
    remarks: "Construction progressing as planned",
    fundDetails: {
      allocated: "Rs. 2,50,000",
      released: "Rs. 1,50,000",
      utilized: "Rs. 1,20,000",
      remaining: "Rs. 30,000",
    },
    constructionDetails: {
      foundation: {
        status: "Completed",
        completionDate: "2023-09-15",
      },
      walls: {
        status: "Completed",
        completionDate: "2023-11-20",
      },
      roof: {
        status: "In Progress",
      },
      finishing: {
        status: "Not Started",
      },
    },
  },
  {
    id: 2,
    beneficiaryName: "Karma Lepcha",
    district: "North Sikkim",
    village: "Mangan",
    stage: "Completed",
    progress: 100,
    fundUtilized: "Rs. 2,50,000",
    lat: 27.6527,
    lng: 88.5122,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    lastUpdated: "2023-11-30",
    startDate: "2023-05-15",
    expectedCompletion: "2023-11-30",
    contactNumber: "9876543211",
    aadharNumber: "XXXX-XXXX-5678",
    familyMembers: 5,
    assignedOfficer: "Pema Wangdi",
    remarks: "Construction completed ahead of schedule",
    fundDetails: {
      allocated: "Rs. 2,50,000",
      released: "Rs. 2,50,000",
      utilized: "Rs. 2,50,000",
      remaining: "Rs. 0",
    },
    constructionDetails: {
      foundation: {
        status: "Completed",
        completionDate: "2023-06-20",
      },
      walls: {
        status: "Completed",
        completionDate: "2023-08-15",
      },
      roof: {
        status: "Completed",
        completionDate: "2023-10-10",
      },
      finishing: {
        status: "Completed",
        completionDate: "2023-11-25",
      },
    },
  },
  {
    id: 3,
    beneficiaryName: "Dawa Sherpa",
    district: "West Sikkim",
    village: "Pelling",
    stage: "In Progress",
    progress: 45,
    fundUtilized: "Rs. 90,000",
    lat: 27.317,
    lng: 88.2336,
    images: ["/placeholder.svg?height=300&width=400"],
    lastUpdated: "2024-01-05",
    startDate: "2023-10-01",
    expectedCompletion: "2024-08-15",
    contactNumber: "9876543212",
    aadharNumber: "XXXX-XXXX-9012",
    familyMembers: 3,
    assignedOfficer: "Tashi Namgyal",
    remarks: "Slight delay due to material shortage",
    fundDetails: {
      allocated: "Rs. 2,50,000",
      released: "Rs. 1,20,000",
      utilized: "Rs. 90,000",
      remaining: "Rs. 30,000",
    },
    constructionDetails: {
      foundation: {
        status: "Completed",
        completionDate: "2023-11-10",
      },
      walls: {
        status: "In Progress",
      },
      roof: {
        status: "Not Started",
      },
      finishing: {
        status: "Not Started",
      },
    },
  },
  {
    id: 4,
    beneficiaryName: "Pema Dorjee",
    district: "South Sikkim",
    village: "Namchi",
    stage: "Completed",
    progress: 100,
    fundUtilized: "Rs. 2,50,000",
    lat: 27.1667,
    lng: 88.3639,
    images: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    lastUpdated: "2023-10-20",
    startDate: "2023-04-01",
    expectedCompletion: "2023-10-15",
    contactNumber: "9876543213",
    aadharNumber: "XXXX-XXXX-3456",
    familyMembers: 6,
    assignedOfficer: "Sonam Gyatso",
    remarks: "Construction completed as planned",
    fundDetails: {
      allocated: "Rs. 2,50,000",
      released: "Rs. 2,50,000",
      utilized: "Rs. 2,50,000",
      remaining: "Rs. 0",
    },
    constructionDetails: {
      foundation: {
        status: "Completed",
        completionDate: "2023-05-10",
      },
      walls: {
        status: "Completed",
        completionDate: "2023-07-15",
      },
      roof: {
        status: "Completed",
        completionDate: "2023-08-30",
      },
      finishing: {
        status: "Completed",
        completionDate: "2023-10-10",
      },
    },
  },
  {
    id: 5,
    beneficiaryName: "Sonam Tamang",
    district: "East Sikkim",
    village: "Pakyong",
    stage: "Delayed",
    progress: 20,
    fundUtilized: "Rs. 50,000",
    lat: 27.2308,
    lng: 88.6924,
    images: ["/placeholder.svg?height=300&width=400"],
    lastUpdated: "2024-01-10",
    startDate: "2023-09-15",
    expectedCompletion: "2024-07-30",
    contactNumber: "9876543214",
    aadharNumber: "XXXX-XXXX-7890",
    familyMembers: 4,
    assignedOfficer: "Karma Dorjee",
    remarks: "Significant delay due to weather conditions",
    fundDetails: {
      allocated: "Rs. 2,50,000",
      released: "Rs. 75,000",
      utilized: "Rs. 50,000",
      remaining: "Rs. 25,000",
    },
    constructionDetails: {
      foundation: {
        status: "Completed",
        completionDate: "2023-11-05",
      },
      walls: {
        status: "In Progress",
      },
      roof: {
        status: "Not Started",
      },
      finishing: {
        status: "Not Started",
      },
    },
  },
]

// Dummy officers data
export const officers: Officer[] = [
  {
    id: 1,
    name: "Karma Dorjee",
    designation: "Junior Engineer",
    district: "East Sikkim",
    contactNumber: "9876543001",
    email: "karma.dorjee@example.gov.in",
    assignedHouses: [1, 5, 9, 13],
  },
  {
    id: 2,
    name: "Pema Wangdi",
    designation: "Assistant Engineer",
    district: "North Sikkim",
    contactNumber: "9876543002",
    email: "pema.wangdi@example.gov.in",
    assignedHouses: [2, 6, 10, 14],
  },
  {
    id: 3,
    name: "Tashi Namgyal",
    designation: "Junior Engineer",
    district: "West Sikkim",
    contactNumber: "9876543003",
    email: "tashi.namgyal@example.gov.in",
    assignedHouses: [3, 7, 11, 15],
  },
  {
    id: 4,
    name: "Sonam Gyatso",
    designation: "Assistant Engineer",
    district: "South Sikkim",
    contactNumber: "9876543004",
    email: "sonam.gyatso@example.gov.in",
    assignedHouses: [4, 8, 12],
  },
]

